### ISSUE TITLE
来自一个被安利的新手爬虫

### ISSUE THREAD

**Issue by liqiang-125** [ydf0509/distributed_framework#1]
如果我使用python自带队列作为中间件，我有一个列表，怎么才能把这个列表当成队列从里边取东西。
然后就是如果consumer = get_consumer（）这个对象成功生成了，该怎么使用呢？是生成对象程序就已经完成了么？

**Comment by liqiang-125** [comment]
> 怎么才能把这个列表当成从从边边取

把这个列表当成队列从中取东西

**Comment by liqiang-125** [comment]
> 如果我使用python自带一体物作为中间件，我有一个列表，怎么才能把这个列表当成从从边边取东西。
> 然后就是如果consumer = get_consumer（）这个对象成功生成了，该怎么使用呢？是生成对象程序就已经完成了么？

怎么把这个列表当成队列从中取东西

**Comment by ydf0509** [comment]
对，get_consumer就行了，按照操作文档的例子就行了，只需要要改broker_kind就可以自动使用不同中间件。所有中间件类型的队列都是全自动的，并不需要用户自己操心怎么新建一个和怎么维护队列。另外说明一下，python内置queue对象作为队列，说的是queue.Queue类型，而不是你说的list列表。

**Comment by ydf0509** [comment]
不是生成对象就完了，consumer = get_consumer（）。之后还需要运行consumer.start_consuming_messege(),这才是启动消费。
