### ISSUE TITLE
get_consumer和fsdf_background_scheduler配合使用的问题

### ISSUE THREAD

**Issue by HrzTester** [ydf0509/distributed_framework#10]
get_consumer和fsdf_background_scheduler配合使用时，提示：AttributeError: 'PersistQueueConsumer' object has no attribute 'is_decorated_as_consume_function'

是fsdf_background_scheduler不能和get_consumer一起用只能使用装饰器版本么？

测试代码：
def test_job():
    from datetime import datetime
    print(f"{datetime.now()}任务执行了一次")

if __name__ == "__main__":
    ss = get_consumer(consuming_function=test_job, queue_name='test_job', broker_kind=BrokerEnum.SQLACHEMY,
                 create_logger_file=False, log_level=10)
    cron = "0/5 * * * * ? *".split(' ')
    cron_rel = dict(second=cron[0], minute=cron[1], hour=cron[2], day=cron[3],
                    month=cron[4]) 
    fsdf_background_scheduler.add_job(timing_publish_deco(ss), trigger='cron',  **cron_rel)
    fsdf_background_scheduler.start()
    ss.start_consuming_message()

如下代码报错：
\lib\site-packages\function_scheduling_distributed_framework\timing_job\__init__.py", line 17, in _deco
    if getattr(consuming_func_decorated_or_consumer, 'is_decorated_as_consume_function') is True:
AttributeError: 'PersistQueueConsumer' object has no attribute 'is_decorated_as_consume_function'

**Comment by ydf0509** [comment]
```python
import datetime
from function_scheduling_distributed_framework import task_deco, BrokerEnum, fsdf_background_scheduler, timing_publish_deco


@task_deco('queue_test_666', broker_kind=BrokerEnum.LOCAL_PYTHON_QUEUE)
def consume_func(x, y):
    print(f'{x} + {y} = {x + y}')


if __name__ == '__main__':
    fsdf_background_scheduler.add_job(timing_publish_deco(consume_func), 'interval', id='3_second_job', seconds=3, kwargs={"x": 5, "y": 6})  # 每隔3秒发布一次任务，自然就能每隔3秒消费一次任务了。
    fsdf_background_scheduler.add_job(timing_publish_deco(consume_func), 'date', run_date=datetime.datetime(2020, 7, 24, 13, 53, 6), args=(5, 6,))  # 定时，只执行一次
    fsdf_background_scheduler.add_timing_publish_job(consume_func, 'cron', day_of_week='*', hour=14, minute=51, second=20, args=(5, 6,))  # 定时，每天的11点32分20秒都执行一次。
    # 启动定时
    fsdf_background_scheduler.start()

    # 启动消费
    consume_func.consume()

  ```

**Comment by ydf0509** [comment]
```python
def timing_publish_deco(consuming_func_decorated_or_consumer: Union[callable, AbstractConsumer]):
    def _deco(*args, **kwargs):
        if getattr(consuming_func_decorated_or_consumer, 'is_decorated_as_consume_function') is True:
            consuming_func_decorated_or_consumer.push(*args, **kwargs)
        elif isinstance(consuming_func_decorated_or_consumer, AbstractConsumer):
            consuming_func_decorated_or_consumer.publisher_of_same_queue.push(*args, **kwargs)
        else:
            raise TypeError('consuming_func_decorated_or_consumer 必须是被 task_deco 装饰的函数或者consumer类型')

    return _deco

```
修改了一下，原来是
```python

def timing_publish_deco(consuming_func_decorated_or_consumer: Union[callable, AbstractConsumer]):
    def _deco(*args, **kwargs):
        if getattr(consuming_func_decorated_or_consumer, 'is_decorated_as_consume_function',False) is True:
            consuming_func_decorated_or_consumer.push(*args, **kwargs)
        elif isinstance(consuming_func_decorated_or_consumer, AbstractConsumer):
            consuming_func_decorated_or_consumer.publisher_of_same_queue.push(*args, **kwargs)
        else:
            raise TypeError('consuming_func_decorated_or_consumer 必须是被 task_deco 装饰的函数或者consumer类型')

    return _deco

```
现在不会报错了，赋值了一个默认值了。
谢谢，传递Consumer类型对象而不是传递被task_deco装饰的消费函数时候，这里有个bug。
下次发布pypi就修改这里，你目前可以getattr那里修改下源码加个False来解决。

**Comment by HrzTester** [comment]
一个新的问题，在重写了timing_publish_deco()方法后，实现代码示例如下，将init_job()放到web框架中进行启动初始化后，
在打印了 “ 操作系统类型是  nt”后，启动过程终止 `Process finished with exit code 1` 没有任何异常，web框架启动容器为`uvicorn`
```python
def test_job(*args):
    from datetime import datetime
    logger.info(f"{datetime.now()}任务执行了一次, 参数")
job_list = [{"job_id": "test_job", "job": test_job, "cron": "0/5 * * * * ? *", "name": "测试",},]

def init_job():
    for i in job_list:
        params = {
            "queue_name": i.get('job_id'),
            "consuming_function": i.get('job'),
            "broker_kind": BrokerEnum.PERSISTQUEUE,
            "log_level": 20,
            "msg_expire_senconds": 30,
        }
        consumer = get_consumer(**params)
        res = fsdf_background_scheduler.get_job(job_id=i.get("job_id"))
        if res:
            return None
        cron = i.get("cron").split(' ')
        cron_rel = dict(second=cron[0], minute=cron[1], hour=cron[2], day=cron[3],
                        month=cron[4]) 
        fsdf_background_scheduler.add_job(timing_publish_deco(consumer), id=i.get("job_id"), trigger='cron',
                          replace_existing=True,   name=i.get("name"), **cron_rel) 

        fsdf_background_scheduler.start()


        # 启动消费
        consumer.start_consuming_message()
```

**Comment by ydf0509** [comment]
"cron": "0/5 * * * * ? *"    这个什么意思。init_job(）不放在web框架中进行启动，就能运行？

**Comment by HrzTester** [comment]
为了统一注册，cron表达式通过如下代码做了解析
```python
cron = i.get("cron").split(' ')
cron_rel = dict(second=cron[0], minute=cron[1], hour=cron[2], day=cron[3], month=cron[4]) 
```

**Comment by HrzTester** [comment]
init_job(）不放在web框架中进行启动，直接运行时可以的
![image](https://user-images.githubusercontent.com/23736521/116237690-205e1580-a793-11eb-9171-a7e94520415c.png)

**Comment by ydf0509** [comment]
那就先说下 系统，是linux还是win

**Comment by ydf0509** [comment]
uvicorn需要windwos运行吧。你是win系统，和我这个框架没关系。

**Comment by HrzTester** [comment]
web框架fastapi，系统：win，fastapi启动就是依赖uvicorn，`uvicorn main:app --reload`
https://fastapi.tiangolo.com/

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/116239100-d7a75c00-a794-11eb-9c84-de6fccbd7ec0.png)

**Comment by ydf0509** [comment]
你用uvicorn启动需要在linux或者mac才能用。

**Comment by ydf0509** [comment]
那要截个图，看看你是怎么组织代码的。先把调用init_job() 不放在if name == main里面，或者代码结尾价格sleep(100000) sleep十万秒试试。

**Comment by ydf0509** [comment]
而且一般来说要分离启动的好，在另外一个脚本启动消费和定时，web框架里面使用  消费函数.push(),一般都是推荐这么运行的，web的启动和后台消费的启动是分独立的两次启动，web中只管push消息到中间件就行了，web中不要启动后台消费。

**Comment by HrzTester** [comment]
尝试过在init_job方法中仅包含consumer，或者仅包含fsdf_background_scheduler部分，但启动都是中断，代码组织的一个demo
https://fastapi.tiangolo.com/advanced/events/?h=startup
```python
from fastapi import FastAPI
from work imort init_job

app = FastAPI()

items = {}

@app.on_event("startup")
async def startup_event():
    items["foo"] = {"name": "Fighters"}
    items["bar"] = {"name": "Tenders"}
    init_job()


@app.get("/items/{item_id}")
async def read_items(item_id: str):
    return items[item_id]
````

启动
if __name__ == '__main__':
    uvicorn.run("main:app", host='127.0.0.1', port=8089,  reload=True, use_colors=True)

**Comment by ydf0509** [comment]
不知道你玩过celery + web没，强烈建议消费和web分两次启动。

**Comment by ydf0509** [comment]
1
