### ISSUE TITLE
请教大神，这个框架在fastapi中如何使用？

### ISSUE THREAD

**Issue by github-ljx** [ydf0509/distributed_framework#13]

**Comment by ydf0509** [comment]
1/启动fastapi，在api接口里面，调用被装饰器装饰的那个task_fun.push任务到消息中间件
2/启动task_fun.consume()

因为发布和消费是解耦的，不是直接调用函数，所以发布和消费可以分开独立部署两次。

**Comment by ydf0509** [comment]
详见例子  test_frame\use_in_flask_tonardo_fastapi
