### ISSUE TITLE
是否支持任务的暂停与继续，以及主任务子任务的编排！

### ISSUE THREAD

**Issue by leeworker** [ydf0509/distributed_framework#14]
您好作者，偶然看到这个很优秀的任务框架，最近我们也是打算迁移重构我们之前的老的任务。也调研了celery 和rq。今天发现您这个框架。简单看了下，想问下这个任务框架是否支持 类似celery的chord 。我们现在期望的功能包括一个 任务能挂起，和失败后，人工介绍，任务继续重试往下。希望您有时间解答下。谢谢。

**Comment by ydf0509** [comment]
有重试的，看参数就知道能指定重试次数。重试是自动的，默认不指定次数就是重试3次。

**Comment by ydf0509** [comment]
你qq

**Comment by leeworker** [comment]
1778878110 你好加一下

**Comment by leeworker** [comment]
作者为啥我加你qq 聊两句，腾讯把我qq号封了。。。现在登陆不上了
