### ISSUE TITLE
请问查看任务消费状态web页面怎样启动呢

### ISSUE THREAD

**Issue by yuanyuanzijin** [ydf0509/distributed_framework#16]
https://i.niupic.com/images/2019/09/20/_331.png

**Comment by ydf0509** [comment]
这个web是单独启动的，并且需要在@desk_task需要设置  function_result_status_persistance_conf 里面的保存结果为True才可以。

**Comment by yuanyuanzijin** [comment]
截图里的这个web页面不包含在项目里，需要自己实现是吗

**Comment by ydf0509** [comment]
https://function-scheduling-distributed-framework.readthedocs.io/zh_CN/latest/articles/c4.html   详见文档4,。10 ，先升级框架到最新版本
