### ISSUE TITLE
windows生产部署

### ISSUE THREAD

**Issue by mn3711698** [ydf0509/distributed_framework#2]
有个windows生产服务器，需要用到异步任务调试，想向您了解一下如何生产部署
代码结构如下
#####sync.py
from function_scheduling_distributed_framework import get_consumer,patch_frame_config,ConsumersManager,show_frame_config
patch_frame_config(REDIS_HOST='127.0.0.1',REDIS_PASSWORD='',REDIS_PORT=6379,REDIS_DB=0)
def send_to_submit(strdata,returntime):
       print(strdata,returntime)

consumer_submit = get_consumer('send_to_submit', consuming_function=send_to_submit, broker_kind=2)
if __name__ == '__main__':
        consumer_submit.start_consuming_message()

我是不是直接在控制台执行python sync.py  命令就可以了呢？

**Comment by mn3711698** [comment]
直接运行python sync.py 这个命令是否可靠，有没有其他的方法？

**Comment by ydf0509** [comment]
pycharm和cmd都可以运行的。和正常脚本部署一样，平时你怎么运行py脚本怎么部署，这个一样的方式。
