### ISSUE TITLE
请问大牛可以把介绍截图里任务消费状态web页面一起加入到仓库中或者提供一个mongo数据格式说明吗，万分感谢

### ISSUE THREAD

**Issue by DJMIN** [ydf0509/distributed_framework#20]
请问大牛可以把介绍截图里任务消费状态web页面一起加入到仓库中或者提供一个mongo数据格式说明吗，万分感谢

**Comment by ydf0509** [comment]
可以的，那个是在家里笔记本里面，我这几天把他上传上来。

**Comment by ydf0509** [comment]
已近加上了这个页面的代码和开启方式。 详见4.10文档。

https://function-scheduling-distributed-framework.readthedocs.io/zh_CN/latest/articles/c4.html

pip 把框架升级到最新版本。

**Comment by DJMIN** [comment]
Error while finding module specification for 'function_scheduling_distributed_framework.function_result_web.app' (ModuleNotFoundError: No module named 'function_scheduling_distributed_framework.function_result_web')
好像还没有诶，是不是还在完善没有全部上传页面

**Comment by ydf0509** [comment]
没上传git，是直接发布到pypi的，你pip升级就可以了。启动时候按照文档说的就行，并不需要把web代码下载下来亲自启动web，pip安装后，直接启动命令行就能启动web了。
