### ISSUE TITLE
请问可以支持调整任务队列的size吗

### ISSUE THREAD

**Issue by DJMIN** [ydf0509/distributed_framework#21]
假设我的爬虫在消费者里依据返回数据持续对redis的任务队列通过push加入新的自动扩线任务，当消费者速度跟不上生产速度会不会导致任务队列无限膨胀，吃光内存。
我希望有一个方法可以在消费者里快速读取当前任务队列的长度，超过一定长度则阻塞当前消费者或者抛弃任务。

**Comment by ydf0509** [comment]
本来就是有界队列，不会迅速从redis拉取100万任务到python内存里面的，如果是这样的，那就后启动的消费者始终消费不到任务，不可能设计成这样的。这点放心，因为这使用的是有界线程/协程池，你说的那种迅速掏空reids因为使用的是官方concurrent.futures.Threadpolexecutor了才会发生这种悲剧。

告实时接口可以设置多少秒后才轮到消费就丢弃任务，文档已近说明了。

**Comment by ydf0509** [comment]
任务队列的size不需要你来手动调整，不希望暴露过多自定义参数。比如你设置并发是100，那么会有100个任务正在并发运行，同时队列会缓存100个任务。所以即使你短时间推送100万任务到消息中间件，也不会迅速掏空的

**Comment by ydf0509** [comment]
本地队列的size默认是等于并发数量。从你描述的，应该是以前有使用官方 concurrent.futures.Threadpolexecutor 的经历，被那个坑惨了，那个总是迅速把redis的任务全部一股脑拿到python的queue对象里面去了，然后慢慢执行。这不科学，不符合负载均衡，不符合多个脚本共享消费。

**Comment by DJMIN** [comment]
哦、那可太好了 ，多谢大牛解答，事实确实如你所说的那样

**Comment by DJMIN** [comment]
哦、那可太好了 ，多谢大牛解答，事实确实如你所说的那样
