### ISSUE TITLE
上下游任务调度

### ISSUE THREAD

**Issue by septfish** [ydf0509/distributed_framework#22]
其他工种的人如何直接发布任务到该框架？如何进行远程调用的？是否像celery 通过flower远程api的调用方式？

**Comment by ydf0509** [comment]
其它工种的人？比如是java人员发布任务到python消费？

**Comment by septfish** [comment]
> 其它工种的人？比如是java人员发布任务到python消费？

是的，这种情况想要实现远程的调用，该怎么办才好呢？
