### ISSUE TITLE
关于任务

### ISSUE THREAD

**Issue by septfish** [ydf0509/distributed_framework#23]
1.是否支持优先级以及如何创建发布优先级任务？
2.消费时间预测是指队列的整个消费时间预估？还是一次任务本身的时间预估？
3.是否像celery一样支持链式任务调用？

**Comment by ydf0509** [comment]
1.没有优先级，可以通过qps调整每个队列的qps运行频率。
2.消费时间预测是指，过去60秒统计运行次数，假如最近60秒完成了100次函数，如果队列嗨剩下1万任务，那么就预计100分钟可以运行完。
3.可以多步骤运行，fun1里面发布任务到fun2里面。https://function-scheduling-distributed-framework.readthedocs.io/zh_CN/latest/articles/c4.html#id4
