### ISSUE TITLE
关于log输出的兼容问题

### ISSUE THREAD

**Issue by RongRongJi** [ydf0509/distributed_framework#24]
您好，我在使用Django+tensorflow+fsdf的架构，但是发现三者同时存在默认的Log会出现错误。
```
python3.6/logging/__init__.py", line 996, in emit    
      stream.write(msg) 
ValueError: I/O operation on closed file.
```
经过测试我发现，只使用Django+fsdf 或者 fsdf+tensorflow 或者 Django + tensorflow 都不会出现异常。
不知道是否是nb_log和某些log同时存在时会出现异常？

**Comment by ydf0509** [comment]
一般这种是想出现了别的主要代码严重错误，然后接着报这个错。礼包你的主代码搞正确，就不会报这个错了，你可以看看代码的上个堆栈报错。

**Comment by ydf0509** [comment]
或者你把堆栈错误截全点

**Comment by ydf0509** [comment]
https://qm.qq.com/cgi-bin/qm/qr?k=unA_o_L3sv5yushJzYGUTAwSzZ7GhUhq&jump_from=webapi   点击链接加群 189603256
