### ISSUE TITLE
定时任务应该如何关闭

### ISSUE THREAD

**Issue by RongRongJi** [ydf0509/distributed_framework#25]
请问使用fsdf_background_scheduler.add_job()添加的定时任务，应该如何删除？

**Comment by RongRongJi** [comment]
使用Apscheduler自带的remove_job，这样似乎在分布式环境下不可行

**Comment by ydf0509** [comment]
apscheduler只是定时发布一个任务到消息队列而已。其他的功能百度apscheduler。
