### ISSUE TITLE
ModuleNotFoundError: No module named 'nb_log_config'

### ISSUE THREAD

**Issue by exp1orer** [ydf0509/distributed_framework#27]
使用pip3 install function_scheduling_distributed_framework安装
运行1.3框架使用示例报错：ModuleNotFoundError: No module named 'nb_log_config'
![image](https://user-images.githubusercontent.com/25338973/127828473-de810e69-8960-4d8b-b581-9a07a1c3e1fc.png)

**Comment by ydf0509** [comment]
export PYTHONPATH=你的项目根目录；python xx.py

在linux或者cmd命令行不能直接python xx.py，

先要设置环境变量，这和框架无关这是python基本常识。你在pycahrm能运行是因为pycahrm自动帮你加了PYTHONPATH。

**Comment by ydf0509** [comment]
我在就知道你们会出这个错误，所以在代码里面都把提示写得这么明确了，你不看控制台打印的提示吗？有点浮躁了
