### ISSUE TITLE
在使用多个步骤的消费函数的时候发布的任务不执行

### ISSUE THREAD

**Issue by Huchengxi** [ydf0509/distributed_framework#28]
在使用多个步骤的消费函数的时候发布的任务不执行，任务队列为空，使用的是redis作为中间件

**Comment by ydf0509** [comment]
是不是分布式环境被别的消费取走了，换个队列名。否则队列为空说明美发部进去，发布消息失败，代码会出错的。

**Comment by Huchengxi** [comment]
嗯嗯，谢谢大佬

**Comment by Huchengxi** [comment]
> 是不是分布式环境被别的消费取走了，换个队列名。否则队列为空说明没发布进去，发布消息失败，代码会出错的。

还有一个问题，就是进程挂久了之后，即使收到任务但是他不会去执行，怎么解决呀，linux和windows都存在这种问题。

**Comment by ydf0509** [comment]
> > 是不是分布式环境被别的消费取走了，换个队列名。否则队列为空说明没发布进去，发布消息失败，代码会出错的。
> 
> 还有一个问题，就是进程挂久了之后，即使收到任务但是他不会去执行，怎么解决呀，linux和windows都存在这种问题。

你是没用我的框架吧？你说的进程运行久了，不运行，那是你自己用redis.blop实现的吧，我这个框架即使用redis做消息中间件不会这样，因为有timeout设置。

**Comment by Huchengxi** [comment]
> > > 是不是分布式环境被别的消费取走了，换个队列名。否则队列为空说明没发布进去，发布消息失败，代码会出错的。
> > 
> > 
> > 还有一个问题，就是进程挂久了之后，即使收到任务但是他不会去执行，怎么解决呀，linux和windows都存在这种问题。
> 
> 你是没用我的框架吧？你说的进程运行久了，不运行，那是你自己用redis.blop实现的吧，我这个框架即使用redis做消息中间件不会这样，因为有timeout设置。

是用的，11.3版本，没有在后台运行 直接挂在前台运行的，然后我用的场景是调起pyppeteer，在并发高的时候 有的浏览器也会死掉。是不是我哪里没配置好

**Comment by ydf0509** [comment]
可以发下你的任务函数看看。前台运行一直是测试环境 开发环境这么做的，pycahrm中运行代码难道不算前台运行吗。

**Comment by Huchengxi** [comment]
> 可以发下你的任务函数看看。前台运行一直是测试环境 开发环境这么做的，pycahrm中运行代码难道不算前台运行吗。

可以加下大佬你的联系方式吗

**Comment by Huchengxi** [comment]
> 可以发下你的任务函数看看。前台运行一直是测试环境 开发环境这么做的，pycahrm中运行代码难道不算前台运行吗。
不会太打扰，就想请教一下解决的方向，我自己太菜，用了这个框架两个月了，自己的问题还没解决，不知道解决的方向。

**Comment by ydf0509** [comment]
> > 可以发下你的任务函数看看。前台运行一直是测试环境 开发环境这么做的，pycahrm中运行代码难道不算前台运行吗。
> > 不会太打扰，就想请教一下解决的方向，我自己太菜，用了这个框架两个月了，自己的问题还没解决，不知道解决的方向。

909686719
