### ISSUE TITLE
是否可以简化启动代码

### ISSUE THREAD

**Issue by mn3711698** [ydf0509/distributed_framework#3]
如果，我有一百个需要处理的任务，那是不是代码有
一百个get_consumer()及一百个start_consuming_message()，能不能简化成为只有一个配置，一个启动？还是说我，我的处理有问题，实际是可以一个配置一个启动就可以 了？

因为我用celery就是一个配置及一个启动就可以了，所以也在想，distributed_framework是不是也能一样

**Comment by ydf0509** [comment]
celery是把所有配置写在一起，比如在一个地方指定10个函数，什么函数绑定什么队列，每个函数的qps，超时杀死等也都是一一指定的。目前此框架没有支持你说的这种读取一个很大的配置的方式，然后启动多个consumer，因为我觉得pycharm及各种ide的智能补全是最重要的，过多基于配置化的设置在现代智能ide里面自动补全提示是不利的，目前的这种启动方式能够在pycahrm很好的智能提示，也利于不用看文档就能很快入手此框架。你说的此框架通过一个一个get_consumer中设置入参来启动，和celery的读取一个很全的配置方式来启动，我认为是此框架和celery框架的使用上的一个非常重大的区别，并且我喜欢当前框架的get_consumer的入参方式作为配置的方式。关于celery的配置方式，我是使用过的，我并不是完全没看过celery，你看我的celery_demo的git项目，就能知道我是用过celery的。

**Comment by ydf0509** [comment]
例如msg_expire_senconds入参指的是消息过期丢弃时间，这个可以在一个分离的配置地方统一指定，如果用户拼写成了msg_expire_sencond，失误拼写少了一个s，那么消息过期丢弃就不能生效。因为配置是分离的，不像函数入参能被ide智能提示和警告，不能被pycharm等智能ide识别拼写中的错误，配置写在统一的地方，我认为这是一种很糟糕的方式。在使用celery上，新手入门门槛高，我认为有两个地方，第一个地方是用户不知道对一个celery消费任务，应该要指定哪些配置和可以指定哪些配置；第二个地方是配置参数容易拼写错误但不能被ide警告出来。此框架的入参方式能很好的解决这两个问题。所以使用方式上不会修改成你说的这样的效果。

**Comment by ydf0509** [comment]
配置写在get_consumer函数里面，比读取一个配置，还能够更好的看出此任务的配置。

**Comment by ydf0509** [comment]
如果你很喜欢统一配置化的方式，我觉得我不需要在框架中加入一个像celery配置方式的启动方式，你可以这么写。
定义一个列表，每个元素是个字典，在字典中指定各个消费任务的配置。

from function_scheduling_distributed_framework import get_consumer

consumer_kwargs_list = [
    {'queue_name': 'queue1', 'consuming_function': f1, 'qps': 10},
    {'queue_name': 'queue2', 'consuming_function': f2, 'qps': 5}
]

for consumer_kwargs in consumer_kwargs_list:
    get_consumer(**consumer_kwargs).start_consuming_message()
