### ISSUE TITLE
是否有类似celery的任务编排功能

### ISSUE THREAD

**Issue by qiyeboy** [ydf0509/distributed_framework#30]

**Comment by ydf0509** [comment]
定时任务吧?什么叫任务编排？
![image](https://user-images.githubusercontent.com/26890690/133417257-94c70603-050b-4089-a8ae-ffc6e20e3daf.png)

**Comment by qiyeboy** [comment]
![image](https://user-images.githubusercontent.com/8142734/133434376-649cff5a-c9af-4126-8a4f-f3c60e3d6a94.png)

**Comment by qiyeboy** [comment]
https://www.escapelife.site/posts/6.3417e+60.html

**Comment by qiyeboy** [comment]
![image](https://user-images.githubusercontent.com/8142734/133434544-a7bd16d9-7a2d-4e02-9e79-706491167f13.png)

**Comment by qiyeboy** [comment]
将多个任务 串并连在一起

**Comment by ydf0509** [comment]
没有支持这种语法，可以多个步骤运行函数。https://function-scheduling-distributed-framework.readthedocs.io/zh_CN/latest/articles/c4.html#id4


没有支持celery group chain 这种语法，可以用其他想法来实现这个目的。
