### ISSUE TITLE
体验

### ISSUE THREAD

**Issue by AlitaIcon** [ydf0509/distributed_framework#32]
用了下且研究了下源码，看的出作者的用心，不过结果获取只能依赖redis，这块可以优化下；另外框架的本身优势完全可以被其它开源框架取代，如果是并发操作的话，这里会有很有任务问题（不列举了）；框架更像是把n个包柔和在一起，层次略微混乱，重点不够突出，不重要的功能过多；一个好的框架一定是把接口留下就可以，实现可以给出默认；测试类要分离；
总结，作者还是很厉害的！希望在代码命名或语义上风格要统一、主要功能要突出点，其次框架本身没有做到真正的分布式，只做到了单点的分布式，分布式意味这单个节点可以集群部署或单节点部署。如果只是单点分布式，意义就不是很大，这里任何消息中间件都可以完成。好在框架本身支持多消费者，过多的功能让我眼花缭乱。。（还是springclound好用）

**Comment by ydf0509** [comment]
这个主要是提供很多任务控制功能，例如任务过滤 qps控频  自动多种并发模式来并发运行，不需要亲自操作消息中间件和操作并发。

这个简单点样子就是，while 1获取消息丢到线程池，但没有啥辅助控制功能。 
```
def start_consuming_message(queue_name, consume_function, threads_num=50):
    """
    本例子实现的功能和中间件过于简单，单一函数最好了。
    看不懂有类的代码，不用看上面那个类，看这个函数就可以，使用一个10行代码的函数实现乞丐版分布式函数执行框架。
    """
    pool = ThreadPoolExecutor(threads_num)
    while True:
        try:
            redis_task = redis_db_frame.brpop(queue_name, timeout=60)
            if redis_task:
                task_str = redis_task[1].decode()
                print(f'从redis的 {queue_name} 队列中 取出的消息是： {task_str}')
                pool.submit(consume_function, **json.loads(task_str))
            else:
                print(f'redis的 {queue_name} 队列中没有任务')
        except redis.RedisError as e:
            print(e)
```

用户当然可以自己操作中间件和操作并发，但每次手写qps控频 过滤 定时，还是很麻烦的。
