### ISSUE TITLE
能否加上一个获得返回值的demo，我使用redis的demo。

### ISSUE THREAD

**Issue by coolkidhai** [ydf0509/distributed_framework#33]
resp = cost_long_time_fun.push("test")
print(resp.status_and_result)
就会卡住到超时，能否像celery样，获得一个taskid，去查询任务状态。返回值获得不到是我操作失误么。
多谢

**Comment by ydf0509** [comment]
> 已经解决，没有设置rpc，感谢作者，真的十分好用

是的，主要是 容易用 性能高，比celery。
