### ISSUE TITLE
RabbitMQ连接不上，找不到能讨论的地方只能来这里了

### ISSUE THREAD

**Issue by ANXIETIER** [ydf0509/distributed_framework#34]
使用REDIS没有问题。

我用的文档 4.1 的代码，装饰器中
`broker_kind=BrokerEnum.PERSISTQUEUE`
改为
`broker_kind=BrokerEnum.RABBITMQ_AMQPSTORM`
之后运行，最后两行提示为

> (192.168.0.107,DESKTOP-N56Q994)-[p14292_t14556] 2021-10-14 17:33:55 - RabbitmqPublisherUsingAmqpStorm--queue_test_f01 - "base_publisher.py:298" - WARNING - 对象的方法 【concrete_realization_of_publish】 首次使用 进行初始化执行 init_broker 方法
> (192.168.0.107,DESKTOP-N56Q994)-[p14292_t14556] 2021-10-14 17:33:55 - RabbitmqPublisherUsingAmqpStorm--queue_test_f01 - "rabbitmq_amqpstorm_publisher.py:23" - WARNING - 使用AmqpStorm包 链接mq

等待一会之后报错如下

> 2021-10-14 17:31:24 - function_error - "D:\Python\Python38\lib\site-packages\function_scheduling_distributed_framework\utils\decorators.py:89" - __handle_exception - ERROR - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> 记录错误日志，调用方法--> [  concrete_realization_of_publish  ] 第  0  次错误重试， 错误类型是：<class 'amqpstorm.exception.AMQPConnectionError'>  Connection timed out
> Traceback (most recent call last):
>   File "D:\Python\Python38\lib\site-packages\function_scheduling_distributed_framework\utils\decorators.py", line 74, in __handle_exception
>     result = func(*args, **keyargs)
>   File "D:\Python\Python38\lib\site-packages\function_scheduling_distributed_framework\publishers\base_publisher.py", line 299, in _deco_mq_conn_error
>     self.init_broker()
>   File "D:\Python\Python38\lib\site-packages\function_scheduling_distributed_framework\publishers\rabbitmq_amqpstorm_publisher.py", line 24, in init_broker
>     self.connection = amqpstorm.UriConnection(
>   File "D:\Python\Python38\lib\site-packages\amqpstorm\uri_connection.py", line 46, in __init__
>     super(UriConnection, self).__init__(hostname, username,
>   File "D:\Python\Python38\lib\site-packages\amqpstorm\connection.py", line 75, in __init__
>     self.open()
>   File "D:\Python\Python38\lib\site-packages\amqpstorm\connection.py", line 224, in open
>     self._wait_for_connection_state(state=Stateful.OPEN)
>   File "D:\Python\Python38\lib\site-packages\amqpstorm\connection.py", line 378, in _wait_for_connection_state
>     raise AMQPConnectionError('Connection timed out')
> amqpstorm.exception.AMQPConnectionError: Connection timed out

然后重新尝试连接，如此重复十次最后达到重试max退出了

文件distributed_frame_config.py中涉及到RabbitMQ的部分我更改为如下内容
```
RABBITMQ_USER = 'guest'
RABBITMQ_PASS = 'guest'
RABBITMQ_HOST = '127.0.0.1'
RABBITMQ_PORT = 15672
RABBITMQ_VIRTUAL_HOST = 'rabbitmq_virtual_host'
```

我确定rabbitMQ已经安装成功，我通过 http://localhost:15672/ 也能进入后台，至于虚拟机我只操作了一步，不知道有没有其他需要操作的地方
![AFJP82@7OC{)SZ9T}@FGDA7](https://user-images.githubusercontent.com/29473224/137292838-908ab8c9-6367-4e36-873b-5b5ce41a81e4.png)

**Comment by ydf0509** [comment]
现在新建了一个群，可以实时了。189603256
