### ISSUE TITLE
worker平滑关闭问题

### ISSUE THREAD

**Issue by bangbao** [ydf0509/distributed_framework#39]
当修改代码要更新worker时， 我希望能给worker发个TERM信号，让当前正在执行的任务完成后在退出， 请求现在支持么？

**Comment by ydf0509** [comment]
支持任何时候随意关闭代码，不会丢失任务。因为是做了消费确认，这个很容易使用sleep 60秒，print hello,在第30秒时候即使你把代码突然关机了，消息也不回丢失，因为还没确认消费。框架非常注重确认消费，文档反复强调了确认消费

**Comment by ydf0509** [comment]
搜索万无一失和确认消费，文档反复强调了这个，说明你还没看文档就开始担忧没这个功能。所有的功能都有，都很容易验证，自己写个函数sleep 60秒，就能验证测试
![image](https://user-images.githubusercontent.com/26890690/144781242-49ad7f43-b502-4040-9344-56c831ccf026.png)

**Comment by ydf0509** [comment]
你说的发个TERM信号没有必要，这不可靠，如果我瞬间突然把你的电脑电源拔掉，哪里还有时间给python代码发信号来处理。确认消费就可以万无一失了。

**Comment by bangbao** [comment]
赞
