### ISSUE TITLE
批量配置后的调用

### ISSUE THREAD

**Issue by mn3711698** [ydf0509/distributed_framework#4]
如：consumer_add = get_consumer('queue_test569', consuming_function=add, broker_kind=9)
我调用的时候是consumer_add.publisher_of_same_queue.publish(dict(x=1,y=2)) 

如您之前建议的定义一个列表，每个元素是个字典，在字典中指定各个消费任务的配置。

from function_scheduling_distributed_framework import get_consumer

consumer_kwargs_list = [
{'queue_name': 'queue1', 'consuming_function': f1, 'qps': 10},
{'queue_name': 'queue2', 'consuming_function': f2, 'qps': 5}
]

for consumer_kwargs in consumer_kwargs_list:
get_consumer(**consumer_kwargs).start_consuming_message()

这样的写法，那我调用的时候要怎么调用？
麻烦写一个完整的例子，谢谢

**Comment by ydf0509** [comment]
你说的应该不是 “调用”二字，应该指的是怎么publish吧。获得发布者对象有多种方式
1/  你有consumer对象了，可以用consumer.publisher_of_same_queue指代发布者。
2/  如果你没有conusmer对象提前，可以用 get_publisher函数生成发布者。

**Comment by mn3711698** [comment]
不知道有没有办法可以一个consumer对象可以publisher_of_same_queue发布所有方法的任务。如果没有，那只能用老办法一个一个处理。

**Comment by ydf0509** [comment]
consumer.publisher_of_same_queue是做了很多处理的，如参数发布检查，自动格式字典/json转换。你可以看一下中间件中的消息，就能知道是消息是什么样的了，目前的消息是比celery消息要简单很多了，你完全可以使用redis.lpush来发布任务。

例如
redis.lpush("queue1",json.dumsp({"a":1,"b":2}))
redis.lpush("queue2",json.dumsp({"x":6}))
