### ISSUE TITLE
新手入门，求个能跑起来的demo

### ISSUE THREAD

**Issue by 89790094** [ydf0509/distributed_framework#40]
新手入门，求个能跑起来的demo

**Comment by ydf0509** [comment]
不是第一页就说明了吗，运行1.3就是了，只有不到8行就能运行demo了。

**Comment by ydf0509** [comment]
> 新手入门，求个能跑起来的demo

还有tests_frame里面的test_xiaoxianrou下载小鲜肉图片你可以学习
