### ISSUE TITLE
请考虑低内存配置的内存占用

### ISSUE THREAD

**Issue by mn3711698** [ydf0509/distributed_framework#5]
此项目确实比celery的执行效率强很多倍，但相对的占用内存也高了，毕竟执行快了，在高并发执行的情况下，内存占用也是个问题。我用一台云主机配置为1C2G3M的centos 7香港线路。因为目前正在研究数字货币，用这台机器与交易所的websocket连接获取交易数据。原来用celery就没有出现过redis挂掉的情况，会出现内存不够用，写入有问题，但不影响使用。改用本库之后，同样的处理，redis扛不过5分钟就挂了。无奈只能不在这台机上做数据存储，只用来接收数据提交到另外一个系统的接口。我试了concurrent_num=10,concurrent_mode=2这两个参数，只是让redis支持的时间久一些，但扛不过10分钟。不知道有没有办法进行设置？

**Comment by ydf0509** [comment]
concurrent_num=2000,时候，每个线程中流转超大字符串会费内存，1g内存机器并发数量应减小到100以下。并发设置超大，反而是会降低效率。
