### ISSUE TITLE
会过滤字符？

### ISSUE THREAD

**Issue by mn3711698** [ydf0509/distributed_framework#6]
{"table":"swap/candle900s","data":[{"candle":["2020-07-10T02:00:00.000Z","9224.3","9230","9224.3","9227.9","2920","31.6394"],"instrument_id":"BTC-USD-SWAP"}]}    这个字符串，经过publisher_of_same_queue.publish(dict(res_str=res_str)) 会少字符

**Comment by ydf0509** [comment]
不会少字符
