### ISSUE TITLE
README示例里都是单机的测试示例，如何在多机情况下测试呢？

### ISSUE THREAD

**Issue by HeLiangHIT** [ydf0509/distributed_framework#7]
RT

**Comment by ydf0509** [comment]
多机和单机反复运行相同脚本多次，效果是一样的。而且你要放在多台机器上运行，代码是不需要做什么变化的，每台机器的代码是一模一样的。多级情况下只要注意使用介绍的真分布式中间件就可以，例如多机情况不要使用python解释器下的queue.Queue和本机磁盘作为中间件。要使用sqalchemy rabbitmq kafka redis等类似这种作为中间件。
