### ISSUE TITLE
web框架中如何使用本框架实现定时调度运行，且多进程下仅被一个进程消费，触发执行？

### ISSUE THREAD

**Issue by HrzTester** [ydf0509/distributed_framework#9]

**Comment by ydf0509** [comment]
对的，代码原理就是定时发一个 消息到消息队列，例如使用redis中间件，就是定时发送一条消息到redis的list，被一个进程消费后就从list  blpop出来了，所以只会被消息一次。例如多进程或者多机器，只会触发一次。难道你是想像广播一样，每个进程每台机器都定时触发执行吗？比如定时发一个邮件，那不需要10几台机器都被触发发导致总共十几次邮件吧，我觉得触发一次就行了。

**Comment by HrzTester** [comment]
谢谢！
另外想了解下如果使用本地存储sqlite3的形式，数据库文件是创建在哪儿的，找了一圈没找到

**Comment by ydf0509** [comment]
distributed frame config.py都是在配置文件里面规定的，配置文件你自己按需修改，如果你没改过，那就是默认在你代码运行所在硬盘的根目录下的persist queues文件夹下，那里面的sqlite3文件可以直接拖拽到pycharm专业版打开。也可以用navicat软件打开查看。每个消息就是表中的一行数据。

**Comment by ydf0509** [comment]
说明你很浮躁，控制台打印的提示和说明非常详细，读取到什么配置了，你肯是没看启动时候的控制台打印。

**Comment by HrzTester** [comment]
看了也搜了控制台日志，确实没找到我关注的数据库文件创建日志记录
阅读了文档，以及distributed_frame_config.py说明，想知道两个点怎么设置：
1、在使用BrokerEnum.SQLACHEMY时，怎么将sqlite3数据库文件创建到项目文件下
2、由于在demo中，当create_logger_file=True时，没发现日志文件，故想知道日志支持统一输出到项目日志文件不

python用得不熟，见谅

**Comment by ydf0509** [comment]
2、你项目根目录下的 nb_log_config 里面可以指定文件位置。如果你没重新指定位置，那么框架就会在 F盘 创建这个文件夹 \pythonlogs。  前提是你的代码是在f盘的任意层级文件夹下面，如果你的代码是放在c盘的任意层级文件夹下面，那么在c盘根目录就有pythonlogs文件夹。  就是你项目脚本不需要放在硬盘根目录，你代码是是什么盘就是生成在什么盘下面。
1、用sqlite3模式就用persistqueue模式就好了，比BrokerEnum.SQLACHEMY 里面配置sqlite3 url好配置多了。除非你是用oracle mysql做消息中间件才使用BrokerEnum.SQLACHEMY 作为中间件。

框架所有的都是给了一个默认值，你按需修改生成的配置文件就行了。sqlite3的位置可以自定义，同理对于redis，比如如果你用redis作为中间件，默认是本机的ip redis无密码，如果你要自定义db ip 密码，就需要修改配置文件了。此框架全部都开放了用户自定义配置，只不过默认有一个配置而已。
